//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CobranzasModel", "FK_Deudor_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(cobranzasoft.Models.Cliente), "Deudor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(cobranzasoft.Models.Deudor), true)]

#endregion

namespace cobranzasoft.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CobranzasEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CobranzasEntities2 object using the connection string found in the 'CobranzasEntities2' section of the application configuration file.
        /// </summary>
        public CobranzasEntities2() : base("name=CobranzasEntities2", "CobranzasEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CobranzasEntities2 object.
        /// </summary>
        public CobranzasEntities2(string connectionString) : base(connectionString, "CobranzasEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CobranzasEntities2 object.
        /// </summary>
        public CobranzasEntities2(EntityConnection connection) : base(connection, "CobranzasEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Deudor> Deudor
        {
            get
            {
                if ((_Deudor == null))
                {
                    _Deudor = base.CreateObjectSet<Deudor>("Deudor");
                }
                return _Deudor;
            }
        }
        private ObjectSet<Deudor> _Deudor;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Deudor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDeudor(Deudor deudor)
        {
            base.AddObject("Deudor", deudor);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CobranzasModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="idCliente">Initial value of the idCliente property.</param>
        /// <param name="nomCliente">Initial value of the nomCliente property.</param>
        /// <param name="codCliente">Initial value of the codCliente property.</param>
        public static Cliente CreateCliente(global::System.Int32 idCliente, global::System.String nomCliente, global::System.String codCliente)
        {
            Cliente cliente = new Cliente();
            cliente.idCliente = idCliente;
            cliente.nomCliente = nomCliente;
            cliente.codCliente = codCliente;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                if (_idCliente != value)
                {
                    OnidClienteChanging(value);
                    ReportPropertyChanging("idCliente");
                    _idCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCliente");
                    OnidClienteChanged();
                }
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomCliente
        {
            get
            {
                return _nomCliente;
            }
            set
            {
                OnnomClienteChanging(value);
                ReportPropertyChanging("nomCliente");
                _nomCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomCliente");
                OnnomClienteChanged();
            }
        }
        private global::System.String _nomCliente;
        partial void OnnomClienteChanging(global::System.String value);
        partial void OnnomClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codCliente
        {
            get
            {
                return _codCliente;
            }
            set
            {
                OncodClienteChanging(value);
                ReportPropertyChanging("codCliente");
                _codCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codCliente");
                OncodClienteChanged();
            }
        }
        private global::System.String _codCliente;
        partial void OncodClienteChanging(global::System.String value);
        partial void OncodClienteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobranzasModel", "FK_Deudor_Cliente", "Deudor")]
        public EntityCollection<Deudor> Deudor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Deudor>("CobranzasModel.FK_Deudor_Cliente", "Deudor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Deudor>("CobranzasModel.FK_Deudor_Cliente", "Deudor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CobranzasModel", Name="Deudor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Deudor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Deudor object.
        /// </summary>
        /// <param name="idDeudor">Initial value of the idDeudor property.</param>
        /// <param name="codDeudor">Initial value of the codDeudor property.</param>
        /// <param name="nomDeudor">Initial value of the nomDeudor property.</param>
        /// <param name="tipDocumento">Initial value of the tipDocumento property.</param>
        /// <param name="numDocumento">Initial value of the numDocumento property.</param>
        /// <param name="fecRegistro">Initial value of the fecRegistro property.</param>
        /// <param name="fecActualizar">Initial value of the fecActualizar property.</param>
        /// <param name="flgActivo">Initial value of the flgActivo property.</param>
        public static Deudor CreateDeudor(global::System.Int32 idDeudor, global::System.String codDeudor, global::System.String nomDeudor, global::System.String tipDocumento, global::System.String numDocumento, global::System.DateTime fecRegistro, global::System.DateTime fecActualizar, global::System.Boolean flgActivo)
        {
            Deudor deudor = new Deudor();
            deudor.idDeudor = idDeudor;
            deudor.codDeudor = codDeudor;
            deudor.nomDeudor = nomDeudor;
            deudor.tipDocumento = tipDocumento;
            deudor.numDocumento = numDocumento;
            deudor.fecRegistro = fecRegistro;
            deudor.fecActualizar = fecActualizar;
            deudor.flgActivo = flgActivo;
            return deudor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDeudor
        {
            get
            {
                return _idDeudor;
            }
            set
            {
                if (_idDeudor != value)
                {
                    OnidDeudorChanging(value);
                    ReportPropertyChanging("idDeudor");
                    _idDeudor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDeudor");
                    OnidDeudorChanged();
                }
            }
        }
        private global::System.Int32 _idDeudor;
        partial void OnidDeudorChanging(global::System.Int32 value);
        partial void OnidDeudorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codDeudor
        {
            get
            {
                return _codDeudor;
            }
            set
            {
                OncodDeudorChanging(value);
                ReportPropertyChanging("codDeudor");
                _codDeudor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codDeudor");
                OncodDeudorChanged();
            }
        }
        private global::System.String _codDeudor;
        partial void OncodDeudorChanging(global::System.String value);
        partial void OncodDeudorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomDeudor
        {
            get
            {
                return _nomDeudor;
            }
            set
            {
                OnnomDeudorChanging(value);
                ReportPropertyChanging("nomDeudor");
                _nomDeudor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomDeudor");
                OnnomDeudorChanged();
            }
        }
        private global::System.String _nomDeudor;
        partial void OnnomDeudorChanging(global::System.String value);
        partial void OnnomDeudorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipDocumento
        {
            get
            {
                return _tipDocumento;
            }
            set
            {
                OntipDocumentoChanging(value);
                ReportPropertyChanging("tipDocumento");
                _tipDocumento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipDocumento");
                OntipDocumentoChanged();
            }
        }
        private global::System.String _tipDocumento;
        partial void OntipDocumentoChanging(global::System.String value);
        partial void OntipDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numDocumento
        {
            get
            {
                return _numDocumento;
            }
            set
            {
                OnnumDocumentoChanging(value);
                ReportPropertyChanging("numDocumento");
                _numDocumento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numDocumento");
                OnnumDocumentoChanged();
            }
        }
        private global::System.String _numDocumento;
        partial void OnnumDocumentoChanging(global::System.String value);
        partial void OnnumDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecRegistro
        {
            get
            {
                return _fecRegistro;
            }
            set
            {
                OnfecRegistroChanging(value);
                ReportPropertyChanging("fecRegistro");
                _fecRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecRegistro");
                OnfecRegistroChanged();
            }
        }
        private global::System.DateTime _fecRegistro;
        partial void OnfecRegistroChanging(global::System.DateTime value);
        partial void OnfecRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecActualizar
        {
            get
            {
                return _fecActualizar;
            }
            set
            {
                OnfecActualizarChanging(value);
                ReportPropertyChanging("fecActualizar");
                _fecActualizar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecActualizar");
                OnfecActualizarChanged();
            }
        }
        private global::System.DateTime _fecActualizar;
        partial void OnfecActualizarChanging(global::System.DateTime value);
        partial void OnfecActualizarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean flgActivo
        {
            get
            {
                return _flgActivo;
            }
            set
            {
                OnflgActivoChanging(value);
                ReportPropertyChanging("flgActivo");
                _flgActivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("flgActivo");
                OnflgActivoChanged();
            }
        }
        private global::System.Boolean _flgActivo;
        partial void OnflgActivoChanging(global::System.Boolean value);
        partial void OnflgActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                OnidClienteChanging(value);
                ReportPropertyChanging("idCliente");
                _idCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCliente");
                OnidClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _idCliente;
        partial void OnidClienteChanging(Nullable<global::System.Int32> value);
        partial void OnidClienteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobranzasModel", "FK_Deudor_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("CobranzasModel.FK_Deudor_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("CobranzasModel.FK_Deudor_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("CobranzasModel.FK_Deudor_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("CobranzasModel.FK_Deudor_Cliente", "Cliente", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
